site_name: "The D3LT4 Protocol"
site_description: "Guías de hacking ético y tutoriales de ciberseguridad"
site_author: Martin Terribile
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode.

    - scheme: default  
      primary: black 
      accent: blue   
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode.
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.lines
    - content.figures
    - header.autohide
  language: es
  favicon: assets/favicon.png
  icon:
    logo: material/lock
  extra:
    analytics:
      provider: Google
      property: G-E7T6RDTQNB
      feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >- 
              Thanks for your feedback! Help us improve this page by
              using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

nav:
  - Inicio: index.md
  - Máquinas Vulnerables:
      - maquinas-vulnerables/index.md
      - DockerLabs:
          - Muy Fácil:
              - maquinas-vulnerables/dockerlabs/muyFacil/injection.md
              - maquinas-vulnerables/dockerlabs/muyFacil/firsthacking.md
          - Fácil:
              - maquinas-vulnerables/dockerlabs/facil/amor.md
  - Cyberdefenders:
      - Endpoint Forensics:
        - cyberdefenders/endpoint-forensics/insider.md
        - cyberdefenders/endpoint-forensics/redline-stealer-lab.md
        - cyberdefenders/endpoint-forensics/ramnit-lab.md
        - cyberdefenders/endpoint-forensics/reveal-lab.md
      - Network Forensics:
        - cyberdefenders/network-forensics/webstrike-lab.md
        - cyberdefenders/network-forensics/poisoned-credentials-lab.md
        - cyberdefenders/network-forensics/tomcat-lab.md
      - Threat Intel:
          - cyberdefenders/threat-intel/iceId-lab.md
  - Tutoriales:
      - tutoriales/index.md
      - pfSense:
          - tutoriales/pfSense/primeros-pasos-pfsense.md
          - tutoriales/pfSense/configurar-openVpn-segura.md
      - Docker:
          - tutoriales/Docker/primeros-pasos-docker.md
          - tutoriales/Docker/instalacion-portainer.md
      - Herramientas de Hacking:
          - tutoriales/herramientas-hacking/nmap.md
          - tutoriales/herramientas-hacking/wireshark.md
  - Recursos:
      - recursos/enlaces-utiles.md
  #   - recursos/glosario.md
  #   - recursos/bibliografia.md
  - Acerca de: about.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Delta-39" target="_blank" rel="noopener">D3LT4</a>
